networks:
  inception:
    name: inception
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/wormr/data/wp
      o: bind
  mariadb_data:
    driver: local 
    driver_opts:
      type: none
      device: /home/wormr/data/db
      o: bind

services:
  nginx:
    # image: nginx:latest
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress 
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  wordpress:
    # image: wordpress:latest
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
  mariadb:
    # image: mariadb:latest
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  redis:
    # image: redis:latest
    container_name: redis
    build: ./requirements/bonus/redis
    env_file: .env
    networks:
      - inception
  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server
    ports:
      - "21:21"
      - "20:20"
      - "50000-50005:50000-50005"
    env_file: .env
    volumes:
      - wordpress_data:/home/$FTP_USER/ftp
    networks:
      - inception
    depends_on:
      - wordpress
  tor:
    container_name: tor
    build: ./requirements/bonus/tor
    networks:
      - inception
  adminer:
    container_name: adminer
    build: ./requirements/bonus/Adminer
    networks:
      - inception
  website:
     container_name: website
     build: ./requirements/bonus/static_website
     networks:
         - inception
